###############################
# APPLICATION
###############################
spring.application.name=booksta

###############################
# SERVER
###############################
server.forward-headers-strategy=framework
app.backend.url=${http://localhost:8080}
###############################
# CORS / FRONT
###############################
app.frontend.url=https://booksta-859bc.web.app
app.cors.allowed-origins=https://booksta-859bc.web.app

###############################
# JWT
###############################
jwt.secret=${MyUltraSuperSecretJwtKey1234567890}
jwt.expiration=3600000
jwt.refresh-expiration=604800000

###############################
# GOOGLE LOGIN (Spring Security OAuth2)
###############################
spring.security.oauth2.client.registration.google.client-id=${405866510311-vjn4stk6h30q490486va0buue9q0v294.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${Uh5U74rnkoDojpQJ0pv1QlC3WpNV}

###############################
# JPA (commun)
###############################
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

###############################
# FILE STORAGE
###############################
file.upload-dir=uploads