###############################
# DATABASE (PostgreSQL prod)
###############################
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# Create tables automatically (simple)
spring.jpa.hibernate.ddl-auto=update

# Execute demo data at startup
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-postgres.sql

# Flyway OFF (car Postgres 18)
spring.flyway.enabled=false

###############################
# JPA / Hibernate (prod)
###############################
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.backend.url=${APP_BACKEND_URL}


