###############################
# DATABASE (PostgreSQL prod)
###############################
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Create tables automatically (simple)
spring.jpa.hibernate.ddl-auto=update

# Execute demo data at startup
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-postgres.sql

# Flyway OFF (car Postgres 18)
spring.flyway.enabled=false

###############################
# JPA / Hibernate (prod)
###############################
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect





# URLs (démo)
app.backend.url=${APP_BACKEND_URL:https://booksta.onrender.com}
app.frontend.url=${APP_FRONTEND_URL:https://booksta-859bc.web.app}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://booksta-859bc.web.app}

# upload writable sur Render
file.upload-dir=${FILE_UPLOAD_DIR:/tmp/uploads}

server.port=${PORT:8080}
server.address=0.0.0.0
