###############################
# DATABASE (PostgreSQL prod)
###############################
spring.datasource.url=${postgresql://booksta:vRbbBWrQMYNO0K1v4V53jEzI6Id67fnE@dpg-d6ire4cr85hc73c4qn5g-a/booksta}
spring.datasource.username=${booksta}
spring.datasource.password=${vRbbBWrQMYNO0K1v4V53jEzI6Id67fnE}
spring.datasource.driver-class-name=org.postgresql.Driver

###############################
# JPA / Hibernate (prod)
###############################
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect